[2022-09-08T18:49:57.778+0500] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: expectation_dag.expect_exist manual__2022-09-08T13:49:44.052113+00:00 [queued]>
[2022-09-08T18:49:57.783+0500] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: expectation_dag.expect_exist manual__2022-09-08T13:49:44.052113+00:00 [queued]>
[2022-09-08T18:49:57.783+0500] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T18:49:57.783+0500] {taskinstance.py:1369} INFO - Starting attempt 1 of 1
[2022-09-08T18:49:57.783+0500] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-09-08T18:49:57.797+0500] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): expect_exist> on 2022-09-08 13:49:44.052113+00:00
[2022-09-08T18:49:57.801+0500] {standard_task_runner.py:52} INFO - Started process 1069880 to run task
[2022-09-08T18:49:57.803+0500] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'expectation_dag', 'expect_exist', 'manual__2022-09-08T13:49:44.052113+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/expectation_dag.py', '--cfg-path', '/tmp/tmpbuea3bqp', '--error-file', '/tmp/tmpfcq4myd5']
[2022-09-08T18:49:57.803+0500] {standard_task_runner.py:80} INFO - Job 35: Subtask expect_exist
[2022-09-08T18:49:57.838+0500] {task_command.py:371} INFO - Running <TaskInstance: expectation_dag.expect_exist manual__2022-09-08T13:49:44.052113+00:00 [running]> on host shahroze
[2022-09-08T18:49:57.881+0500] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=expectation_dag
AIRFLOW_CTX_TASK_ID=expect_exist
AIRFLOW_CTX_EXECUTION_DATE=2022-09-08T13:49:44.052113+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-08T13:49:44.052113+00:00
[2022-09-08T18:49:57.883+0500] {logging_mixin.py:115} INFO - {
  "meta": {},
  "success": true,
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "expectation_config": {
    "expectation_type": "expect_column_to_exist",
    "kwargs": {
      "column": "trip_distance",
      "result_format": "BASIC"
    },
    "meta": {}
  },
  "result": {}
}
[2022-09-08T18:49:57.883+0500] {python.py:173} INFO - Done. Returned value was: None
[2022-09-08T18:49:57.888+0500] {taskinstance.py:1407} INFO - Marking task as SUCCESS. dag_id=expectation_dag, task_id=expect_exist, execution_date=20220908T134944, start_date=20220908T134957, end_date=20220908T134957
[2022-09-08T18:49:57.935+0500] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-08T18:49:57.948+0500] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
